# .github/workflows/main.yml
name: Build echo-server

on:
  push:
    branches: [ main ]

permissions: read-all

defaults:
  run:
    shell: bash

env:
  IMAGE_REGISTRY: docker.io
  IMAGE_NAME: ${{ github.event.repository.name }}-echo-server
  
jobs:
  build-and-push:
    outputs:
      image: ${{ steps.image.outputs.image }}
      digest: ${{ steps.build.outputs.digest }}
    permissions:
      packages: write # for uploading attestations.
      contents: read
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871    #v4.2.1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

    - name: Authenticate Docker
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567  #v3.3.0
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: upgradkrithikavenugopal
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81   #v5.5.1
      with:
        images: ${{ env.IMAGE_REGISTRY }}/upgradkrithikavenugopal/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
      id: build
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        context: "{{defaultContext}}:images/echo-server"
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Output image
      id: image
      run: |
          image_name="${{ env.IMAGE_REGISTRY }}/upgradkrithikavenugopal/${{ env.IMAGE_NAME }}"
          echo "image=$image_name" >> "$GITHUB_OUTPUT"

  provenance:
    needs: [build-and-push]
    permissions:
      actions: read # for detecting the Github Actions environment.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.0.0
    with:
      image: ${{ needs.build-and-push.outputs.image }}
      digest: ${{ needs.build-and-push.outputs.digest }}
      registry-username: upgradkrithikavenugopal

    secrets:
      registry-username: upgradkrithikavenugopal
      registry-password: ${{ secrets.REGISTRY_PASSWORD }}

  run:
    needs: [build-and-push, provenance]
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate Docker
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567  # v3.3.0
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: upgradkrithikavenugopal
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Run it
        env:
          IMAGE: ${{ needs.build-and-push.outputs.image }}
          DIGEST: ${{ needs.build-and-push.outputs.digest }}
        run: |
          docker pull "${IMAGE}@${DIGEST}"
          echo "::warning ${IMAGE}@${DIGEST}"